development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: repo_development
  pool: 5
  username: repo
  password: repo_pass

test: &TEST
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: repo_test
  pool: 5
  username: repo
  password: repo_pass

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: repo_production
  pool: 5
  username: repo
  password: repo_pass
