# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 54a61868fec00f90f9269bb7f0a1c0d84733d5dca9914e52038c8a2bc61f3f49afff83c05129e5500a206dfde7e773980fa2badbd4457019daeb2b3ad09cf491

test:
  secret_key_base: 33663d5f1792efc67229133e06437af6bdeda69b0fe4b32f7f264e6ffe85ac50263cb958e575a163e9da3dccdf4db681d1d82063627d6ee75bda3b56d1cc54a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
